name: Update Rulesets on SIEM
on:
  push:
    branches: [ "main" ]
    paths: ["**.xml"]
  workflow_dispatch:

jobs:
  DaaC:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Network stability timeout
    steps:
      - name: Apply modified or new decoders and rules to SIEM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          timeout: 60s        #  SSH connection timeout
          command_timeout: 3m #  Command execution timeout
          script:
           whoami
