name: Update Rulesets on SIEM
on:
  push:
    branches: [ "main" ]
    paths: ["**.xml"]
  workflow_dispatch:

jobs:
  DaaC:
    runs-on: ubuntu-latest
    steps:
      - name: Apply modified or new decoders and rules to SIEM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo bash -c '
            # Navigate to Docker volume directory
            cd /var/lib/docker/volumes/single-node_wazuh_etc/_data
            
            # Pull latest changes from remote repository
            git pull origin main
            
            # Remove empty XML files to prevent configuration errors
            find /var/lib/docker/volumes/single-node_wazuh_etc/_data/decoders/ -name "*.xml" -size 0 -delete 2>/dev/null || true
            find /var/lib/docker/volumes/single-node_wazuh_etc/_data/rules/ -name "*.xml" -size 0 -delete 2>/dev/null || true
            
            # Set permissions for decoder files if they exist (using UID 999 for container wazuh user)
            if [ -n "$(ls -A decoders/*.xml 2>/dev/null)" ]; then
              docker exec single-node-wazuh.manager-1 chown -R 999:999 /var/ossec/etc/decoders/
              docker exec single-node-wazuh.manager-1 chmod -R 644 /var/ossec/etc/decoders/*.xml
              echo "Decoder file permissions set (UID 999)"
            fi
            
            # Set permissions for rule files if they exist (using UID 999 for container wazuh user)
            if [ -n "$(ls -A rules/*.xml 2>/dev/null)" ]; then
              docker exec single-node-wazuh.manager-1 chown -R 999:999 /var/ossec/etc/rules/
              docker exec single-node-wazuh.manager-1 chmod -R 644 /var/ossec/etc/rules/*.xml
              echo "Rule file permissions set (UID 999)"
            fi
            
            # Validate XML files before restart
            echo "Validating XML files..."
            for file in decoders/*.xml rules/*.xml; do
              if [ -f "$file" ]; then
                if ! xmllint --noout "$file" 2>/dev/null; then
                  echo "❌ Invalid XML file: $file"
                  exit 1
                fi
              fi
            done
            
            # Restart Wazuh manager
            docker exec single-node-wazuh.manager-1 /var/ossec/bin/wazuh-control restart \
            && echo "Ruleset apply SUCCESS!!! - Wazuh manager restarted successfully." \
            || echo "Ruleset apply FAILURE!!! - Wazuh manager failed to restart, check ruleset for error..."
            
            # Verify permissions after restart
            echo "Verifying file ownership..."
            docker exec single-node-wazuh.manager-1 ls -la /var/ossec/etc/decoders/ | head -5
            docker exec single-node-wazuh.manager-1 ls -la /var/ossec/etc/rules/ | head -5
            
            # Check Wazuh manager status
            docker exec single-node-wazuh.manager-1 /var/ossec/bin/wazuh-control status
            '
